name: nodejs-dev-template
services:
  # Node.js 應用程式服務
  app:
    build: .
    image: nodejs-dev-template:${APP_VERSION}
    container_name: nodejs-dev-template
    restart: always
    ports:
      - "3009:3009"
    environment:
      - TZ=Asia/Taipei
      - NODE_ENV=production
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - .env